name: Add Single Unplanned Activity

      env:
        GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |
        # Pass the input ID as an argument to the script
        python python/utils/hydrate_activity.py "${{ github.event.inputs.activity_id }}"
